### ISSUE TITLE
License

### ISSUE THREAD

**Issue by NorielSylvire** [gemartin99/So_long-Tester#1]
Does this repo have a license? I would like to use your maps for my so_long. Do I have your permission to do so? Thanks in advance 😄

**Comment by gemartin99** [comment]
Good afternoon, sorry for the delay in replying. The answer is YES, this repository has been created with the purpose of helping the community of 42, everyone has permission to test the maps. But that if, as long as you know what you are testing. Thanks for asking and greetings :)
